version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo_password
      POSTGRES_DB: project_echo

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
