server:
  port: 8081
spring:
  application:
    name: project-echo
  datasource:
    url: jdbc:postgresql://localhost:5432/project_echo
    username: echo
    password: echo_password
  security:
    user:
      name: admin
      password: "${APP_PASSWORD:adminpwd}"
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
    audit:
      enabled: false

