server:
  port: 8080

spring:
  profiles: prod

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
