global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: "project-echo"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["backend:8080"]
