#!/bin/bash
# 
# Engineering Metrics Collector for YES (Yash Engineering Systems)
# Connects to GitHub API and aggregates DORA metrics and project health.

set -e

if [ -z "$GITHUB_TOKEN" ]; then
  echo "Error: GITHUB_TOKEN is not set."
  exit 1
fi

REPO="yashsiwacha/ProjectEcho"
API_URL="https://api.github.com/repos/$REPO"

echo "================================================="
echo " YES Engineering Metrics Dashboard Generator     "
echo "================================================="

# 1. Fetch Issues Metrics
ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL/issues?state=all&per_page=100")
CLOSED_ISSUES=$(echo "$ISSUES" | jq '[.[] | select(.state=="closed" and .pull_request==null)] | length')
OPEN_BUGS=$(echo "$ISSUES" | jq '[.[] | select(.state=="open" and (.labels[].name=="bug"?))] | length')
OPEN_TECH_DEBT=$(echo "$ISSUES" | jq '[.[] | select(.state=="open" and (.labels[].name=="technical-debt"?))] | length')

# 2. Fetch Release Metrics (Deployment Frequency)
RELEASES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL/releases?per_page=100")
TOTAL_RELEASES=$(echo "$RELEASES" | jq 'length')
# Just an approximation: count releases in the last 30 days
RECENT_RELEASES=$(echo "$RELEASES" | jq '[.[] | select(.published_at > (now - 2592000 | todate))] | length')

# 3. Pull Request Metrics
PRS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL/pulls?state=all&per_page=100")
MERGED_PRS=$(echo "$PRS" | jq '[.[] | select(.merged_at!=null)] | length')

echo "Generating Metrics Report..."
cat <<EOF > engineering_metrics_report.md
# Engineering Metrics Dashboard

## Repository Health
- **Total Releases (Deployments):** $TOTAL_RELEASES
- **Deployments (Last 30 Days):** $RECENT_RELEASES
- **Total Pull Requests Merged:** $MERGED_PRS

## Issue Tracking
- **Issues Closed:** $CLOSED_ISSUES
- **Open Bugs:** $OPEN_BUGS
- **Open Technical Debt Items:** $OPEN_TECH_DEBT

## DORA Estimates
- **Deployment Frequency:** $(if [ "$RECENT_RELEASES" -gt 4 ]; then echo "High (Multiple per week)"; else echo "Medium"; fi)
- **Bug Rate:** $(if [ "$MERGED_PRS" -gt 0 ]; then echo "Scale dynamically"; else echo "N/A"; fi)

*Generated by YES Autonomous Workflow*
EOF

echo "Metrics saved to engineering_metrics_report.md"
