name: CD Pipeline - Koyeb Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline - Build and Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Koyeb Deployment
        run: |
          curl -X POST https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}/redeploy \
               -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"
